pipeline:

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      event:
        - push
      branch:
        - ${DRONE_BRANCH}

  drone_s3_cache_pull:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.2.0
    drone_s3_cache_mode: "pull"
    secrets:
      - DRONE_S3_CACHE_AWS_ACCESS_KEY_ID
      - DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY
      - DRONE_S3_CACHE_BUCKET_NAME

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt --error test docker:stage
    environment:
      - ENV_LOG_LEVEL=ERROR
      - ARTIFACTORY_USERNAME=drt_ci
    secrets:
      - ARTIFACTORY_PASSWORD
      - KEYTOOL_PASSWORD
    when:
      event:
        - push
      branch:
        - ${DRONE_BRANCH}

  build_docker:
    environment:
      - DOCKER_USERNAME=drt_ci
      - DOCKER_HOST=tcp://172.17.0.1:2375
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_BUILD_NUMBER}
      - latest
    when:
      event: push
      branch:
        - ${DRONE_BRANCH}

  cypress-e2e-test:
    image: docker:18.06
    environment:
      - DOCKER_USERNAME=drt_ci
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
      - play
    commands:
      - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker run -m 5g -d --name $${DRONE_COMMIT_SHA} -e ENABLE_STATSD=false -e CONTACT_EMAIL=support@test.com -e OOH_PHONE=012345 -e KEY_CLOAK_URL="https://sso-dev.notprod.homeoffice.gov.uk/auth/admin/realms/drt-notprod" -e JAVA_OPTS="-Xmx4g -Dconfig.resource=application-inmemory.conf" -e USE_API_PAX_NOS=true -e ADJUST_EGATES_USE_BY_U12S=true -e PORT_CODE="test" -e ENV="test" -e FORECAST_MAX_DAYS=2 -e STAGE_THROTTLE_MILLIS=50 -e BASE_DOMAIN=drt-test.homeoffice.gov.uk docker.digital.homeoffice.gov.uk/drt/drt:latest $${PLAY}
      - docker build -t drt-cypress -f cy-drt-dockfile .
      - docker run --net=container:$${DRONE_COMMIT_SHA} -e CYPRESS_baseUrl="http://localhost:9000" drt-cypress /bin/bash -c "npm run test"
    when:
      event: push
      branch: ${DRONE_BRANCH}

  drone_s3_cache_push:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.2.0
    drone_s3_cache_folders:
      - ./.ivy2
      - ./.sbt/boot
      - ./drone/src/github.com/UKHomeOffice/drt-v2/node_modules
    drone_s3_cache_mode: "push"
    secrets:
      - DRONE_S3_CACHE_AWS_ACCESS_KEY_ID
      - DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY
      - DRONE_S3_CACHE_BUCKET_NAME

  git_tag:
    image: alpine/git
    secrets: [ ssh_key ]
    commands:
      - mkdir /root/.ssh/ && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - ssh-keyscan github.com >> /root/.ssh/known_hosts && chmod 600 /root/.ssh/known_hosts
      - printf  "Host github.com\n   Hostname github.com\n   IdentityFile /root/.ssh/id_rsa\n" > /root/.ssh/config
      - chmod 0600 /root/.ssh/config
      - printf "[github]\n[user]\n user = git" > /root/.gitconfig
      - git remote add tag-origin  git@github.com:UKHomeOffice/drt-v2.git
      - git tag ${DRONE_BUILD_NUMBER}
      - git push tag-origin ${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master

  slack_notification:
    image: plugins/slack
    secrets:
      - slack_webhook
    channel: devs
    username: drone
    template: >
      *{{repo.name}}: _{{build.status}}_*

      Completed build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*

      *Triggered by*: _${DRONE_COMMIT_AUTHOR}_

      *Message*: ${DRONE_COMMIT_MESSAGE}

      {{build.link}}
    when:
      status: [ success, failure ]
      branch: master
