pipeline:

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt --error test docker:stage
    environment:
      - ARTIFACTORY_USERNAME=drt_ci
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - [push, tag]
      branch: 
        - drt-acp-pgsql  

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      event:
        - push
      branch: 
        - drt-acp-pgsql   

  build_docker:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: [push, tag]
      branch: 
        - drt-acp-pgsql

  drt-test-instance:
    image: docker:18.06
    environment:
      - DOCKER_USERNAME=drt_ci
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:  
      - docker_password
      - play  
    commands:
      - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker run -d --name $${DRONE_COMMIT_SHA} -e POSTGRES_USER="test_user" -e POSTGRES_DB="test" -e POSTGRES_PASSWORD="test_password" postgres:alpine 
      - docker run  -d --net=container:$${DRONE_COMMIT_SHA} -e KEY_CLOAK_URL="https://sso-dev.notprod.homeoffice.gov.uk/auth/admin/realms/drt-notprod" -e PERSISTENCE_BASE_DIR="/var/lib/drt-v2/live/test" -e PORT_CODE="test" -e DQ_S3_BUCKET="" -e ENV="test" -e POSTGRES_PASSWORD="test_password" -e POSTGRES_HOST="localhost" -e POSTGRES_USER="test_user"  docker.digital.homeoffice.gov.uk/drt/drt:latest bin/drt -Duser.timezone=UTC $${PLAY}
      - docker build -t drt-cypress -f cy-drt-dockfile .
      - docker run  --net=container:$${DRONE_COMMIT_SHA} -e CYPRESS_baseUrl="http://localhost:9000" drt-cypress /bin/bash -c "./node_modules/.bin/cypress run"       

    when:
      event: push
      

  copy-e2e-result:
    image: plugins/s3
    bucket: ${AWS_BUCKET_NAME}
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    source: cypress-result/*
    target: /e2e/   
    when:
      event: push      
      status: failure

  build_tag:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
