version = 3.11.1
runner.dialect = scala213
project.git = true
project.layout = StandardConvention

maxColumn = 120
lineEndings = preserve
style = defaultWithAlign

docstrings.style = Asterisk
docstrings.wrap = false

spaces.inImportCurlyBraces = true

rewrite.rules = [RedundantParens, SortImports]
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

align.preset = some
align.allowOverflow = true
align.openParenDefnSite = false
align.openParenCallSite = false
align.tokens."+"                         = [
  {
    code   = "~>"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  },
  {
    code   = "%"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  },
  {
    code   = "%%"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  }
]

newlines.source = keep
newlines.beforeMultiline = keep
newlines.avoidForSimpleOverflow = [slc]

danglingParentheses.callSite = true
danglingParentheses.defnSite = true

binPack.importSelectors = unfold
binPack.unsafeCallSite = false
binPack.unsafeDefnSite = false

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}